<?php

$GLOBALS['sections'] = array(
	'header'=> array( 
		'name' => 'Header', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'navbar'=> array( 
		'name' => 'Navbar', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'dropdown-menu'=> array( 
		'name' => 'Nav Dropdowns', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'mobileNav'=> array( 
		'name' => 'Mobile Nav', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'sidr'=> array( 
		'name' => 'Side Drawer', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'cycler'=> array( 
		'name' => 'Image Banner', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'pageTitle'=> array( 
		'name' => 'Title Area', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'body'=> array( 
		'name' => 'Body', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'posts'=> array( 
		'name' => 'Post contents', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'footer'=> array( 
		'name' => 'Footer', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'login'=> array( 
		'name' => 'Login Page', 
		'settings' => array('background','borders','text','headings', 'presentation', 'images','misc') ),
	'misc_background'=> array( 
		'name' => 'Special Backgrounds', 
		'settings' => array('htmlTag','bodyTag','mastArea','contentArea') ),
	'page_layouts' => array( 
		'name' => 'Page Layouts',
		'settings' => array('posts','pages','frontPage','attachments') ),
);